
CREATE TABLE CUSTOMERCITYINFO
(
ID   INT,
FIRST_NAME  VARCHAR(20),
LAST_NAME   VARCHAR(25),
EMAIL       NVARCHAR(30),
GENDER      VARCHAR(15),
CITY        VARCHAR(25)
)

SELECT *FROM CUSTOMERCITYINFO

INSERT INTO CUSTOMERCITYINFO VALUES
(1,'HILLIARD','DOWNIE','HDOWNIE0@SLASHDOT.ORG','MALE','NEW YORK')
INSERT INTO CUSTOMERCITYINFO VALUES
(2,'GREG','BACHNIC','GBACHNIC1@FOTKI.COM','MALE','NEW YORK')
INSERT INTO CUSTOMERCITYINFO VALUES
(3,'CINDRA','HISKEY','CHISKEY2@GITHUB.IO','FEMALE','NEW.''YORK')
INSERT INTO CUSTOMERCITYINFO VALUES
(4,'EDUINO','LEPICK','ELEPICK3@WASHINGTONPOST.''COM','MALE','LONDON')
INSERT INTO CUSTOMERCITYINFO VALUES
(5,'LEANNA','MARRIOT','LMARRIOT4@BUSINESSINSIDER.COM','FEMAILE','LONDON')
INSERT INTO CUSTOMERCITYINFO VALUES
(6,'RONALD','MACCROSSAN','RMACROSSAN5@PININTEREST.COM','MALE','SALT LAKE CITY')
INSERT INTO CUSTOMERCITYINFO VALUES 
(7,'CECE','SLEICHT','CSLEICHT6@MEDIAFIRE,COM','MALE','SALTLAKE CITY')
INSERT INTO CUSTOMERCITYINFO VALUES
(8,'VERILE','COCKROFT','VCOCKROFT7@4SHARED.COM','FRMALE','SALT LAKE.''CITY')
INSERT INTO CUSTOMERCITYINFO VALUES
(9,'JUSTINIAN','PHILIP','JPHILP@WISC.EDU','MALE','SALT LAKE CITY')
INSERT INTO CUSTOMERCITYINFO VALUES
(10,'NEALL','MONTFORT','NMONTFORT9@YAHOO.COM','MALE','NEW DELHI')