--DDL (DATA DEFINITION LANGUAGE)

--ALTER
--GENERAL SYNTAX
ALTER TABLE TABLE_NAME ADD COLUMN_NAME DATATYPE -------------------ADDING NEW COLUMN
ALLTER TABLE TABLE_NAME ALTER COLUMN COLUMN_NAME NEW_DATATYPE -------MODIFYING DATATYPE OF COLUMN
ALTER TABLE TABLE_NAME DROP COLUMN COLUMN_NAME --------> DROP COLUMN FROM TABLE


SELECT *FROM STUDENTSINFO

ALTER TABLE STUDENTSINFO ADD CLASS VARCHAR(3) ------must give the datatype of column

ALTER TABLE STUDENTSINFO ALTER COLUMN ROLLNO INT

--Stored Procedure
There is no function in SQL Server to change the name of column
EXEC sp_rename 'OLD_NAME', 'NEW_NAME','NAMEOFOBJECT'

EXEC sp_rename 'Student.ID','RollNo','COLUMN'
--for renaming column name, we must use the table name.

EXEC sp_rename 'Student', 'Student_Info','TABLE' --changing the table name---

--DROP TABLE TABLE_NAME;
--DROP DATABASE DATABASE_NAME,
--DROP PROC PROC_NAME

ALTER TABLE TABLE_NAME DROP COLUMN COLUMN_NAME
ALTER TABLE STUDENT_INFO DROP COLUMN CLASS

DROP TABLE STUDENT_INFO

--DROP TABLE MS_sQL.[dbo].[DocType]
--DROP TABLE SQL_1024.[DBO].[DOCTYPE]

DROP FUNCTION [DBO].INSERT.EMPLOYEEDETAILS]

--Schema is a collection of all database objects

--FULL NAME-----> 3 PART NAME ----> DATABASE.SCHEMA.OBJECT

ALTER TABLE DBO.EMPLOYEE ALTER COLUMN EMPID INT IDENTITY(1,1) NOT NULL
------------------------------------------------------------------

ALTER TABLE STUDENT ADD SUBJECT VARCHAR(15)
ALTER TABLE STUDENT ALTER COLUMN CLASS VARCHAR(10)


EXEC SP_RENAME 'STUDENT.MARKS','TOTAL_MARKS','COLUMN'

EXEC SP_RENAME 'STUDENT','STUDENT_INFO'

ALTER TABLE STUDENT_INFO DROP COLUMN GENDER

DROP is used for dropping any database objects.
Procedure is a set of code/program that is created for performing specific task

CREATE TABLE TBLGENDER
(
ID INT IDENTITY (1,1),
GENDER VARCHAR (6)
)

SELECT *FROM TBLGENDER

INSERT INTO TBLGENDER (GENDER) VALUES ('MALE'),('FEMALE'),('UNK'),(NULL)

TRUNCATE TABLE TBLGENDER

DELETE FROM TBLGENDER WHERE GENDER = 'MALE'

--DIFF BETWEEN DELETE AND TRUNCATE

1.TRUNCATE WILL DO THE IDENTITY RESET BUT DELETE WILL NOT,IT WILL START FROM LAST IDENTITY.
2.TRUNCATE IS DDL BUT DELETE IS DML.
3.TRUNCATE WILL DELETE ENTIRE DATA,FREEUP SPACE AND RESET IDENTITY
4.TRUNCATE IS NOT USED FOR DELETING A PARTICULAR SET OF ROW DATA, IT WILL DELETE ENTIRE DATA
5.DELETE CAN BE USED WITH WHERE BUT TRUNCATE CAN BE USED WITHOUT WHERE.
6.DELETE CAN BE USED TO DELETE ENTIRE ROW IF USED WITHOUT WHERE.

TRUNCATE AND DELETE BOTH ARE USED TO DELETE ROWS ONLY, NOT DATA OF A PARTICULAR COLUMN.

DROP - COLUMN NAME AND WHOLE STRUCTURE IS DELETED.


If we just want to refresh data everyday/not want to run historical data, we use Truncate and Delete.
Eg: college admission registration----insert details like firstname,mobile....submit button -----data will be stored in the table.