--SQL AUTO INCREMENT FIELD

CREATE TABLE PERSONS(
PERSONID INT IDENTITY(1,1) PRIMARY KEY,
LASTNAME VARCHAR (255)NOT NULL,
FIRSTNAME VARCHAR(255),
AGE INT
)

--AUTO INCREMENT
--MS SQL USES IDENTITY KEYWORD FOR AUTO INCREMENT FEATURE
--IDENTITY(STARTVALUE, INCREMENTALVALUE)
--WHENEVER WE DEFINE IDENTITY COLUMN, NO NEED TO SUPPLY VALUE FOR THAT COLUMN DURING INSERT.
--TRUNCATE WILL DO THE IDENTITY RESET ON THE TABLE (IDENTITY VALUE WILL BE RESET TO STARTING VALUE)
--DELETE WILL NOT DO IDENTITY RESET(EVEN IF RECORDS DELETED AND NEW RECORD INSERTED,NEXT VALUE WILL BE ASSIGNED TO IDENTITY COLUMN)
--WE CANNOT SUPPLY VALUE TO THE IDENTITY COLUMN AS IDENTITY_INSERT IS OFF.
--IDENTITY_INSERT IS A SQL FEATURE TO SEE WHETHER IDENTITY VALUES CAN BE SPECIFIED EXPLICITLY DURING INSERT.

-- BY DEFAULT - IDENTITY_INSERT IF OFF WHENEVER WE CREATE IDENTITY COLUMN
--(WE CANNOT INSERT THE VALUES IN THE IDENTITY COLUMN ,THAT ARE AUTOMATICALLY GENERATED)

-- IF YOU WANT TO INSERT EXPLICIT VALUE(IDENTITY VALUE BY YOUR OWN)THEN WE MUST SET THE IDENTITY_INSERT ON 
 SELECT * FROM PERSONS

 INSERT INTO PERSONS VALUES
 (5,'RAJ','WANKAR',33),
 (4,'JYOTI','KHANNA',33),
 (1,'TOM','JERRY',33),
 (2,'SHIV','SHARMA',30)
 
INSERT INTO PERSONS (LASTNAME,FIRSTNAME,AGE)VALUES
 ('WANKAR','SHIVRAJ',29)
 INSERT INTO PERSONS (LASTNAME,FIRSTNAME,AGE)VALUES
 ('PAWAR','YOGI',29)

 INSERT INTO PERSONS VALUES
 ('RAJ','WANKAR',33),
 ('JYOTI','KHANNA',33),
 ('TOM','JERRY',33),
 ('SHIV','SHARMA',30)
 
 

 DELETE FROM PERSONS WHERE PERSONID = 8
 DELETE FROM PERSONS

 --EVERY INSERT --- NEW IDENTITY VALUE = LASTGENERATEDIDENTITYVALUE + INCREMENTAL VALUE

 --WE CANNOT UPDATE IDENTITY COLUMN WHETHER IT HAS PRIMARY KEY OR NOT.
 --DEFAULT VALUE OF IDENTITY COLUMN IS 1,1

 ----WE CANNOT SUPPLY VALUE TO THE IDENTITY COLUMN
 INSERT INTO PERSONS VALUES (2,'ARI','JOSH',39)
An explicit value for the identity column in table 'PERSONS' can only be specified when a column list is used and IDENTITY_INSERT is ON.

SET IDENTITY_INSERT DATABASENAME.SCHEMA.TABLENAME ON
SET IDENTITY_INSERT ZORBA_1024.DBO.PERSONS ON
INSERT INTO PERSONS (PERSONID,LASTNAME,FIRSTNAME,AGE)VALUES (2,'CHAHAL','RAHUL',35)
--Violation of PRIMARY KEY constraint 'PK__PERSONS__0986239EDF8A4167'. Cannot insert duplicate key in object 'dbo.PERSONS'. The duplicate key value is (2).
INSERT INTO PERSONS (PERSONID,LASTNAME,FIRSTNAME,AGE)VALUES (10,'CHAHAL','RAHUL',35)

SET IDENTITY_INSERT ZORBA_1024.DBO.PERSONS OFF

EG: EMPLOYEE 3 LEFT THE JOB, WE WILL DELETE THE RECORD AND IF WE WANT TO USE EMPLOYEEID 3, AT THAT TIME WE CAN INSERT
IDENTITY_INSERT ON AND UPDATE THE ID TO 3 AND AGAIN DO IDENTITY_INSERT OFF.

--AUTO INCREMENT FIELD IS USED WITH PRIMARY KEY

-----------------------------------------------------------------

CREATE TABLE PERSONS(
PERSONID INT IDENTITY(100,1),
LASTNAME VARCHAR (255)NOT NULL,
FIRSTNAME VARCHAR(255),
AGE INT
)

ALTER TABLE PERSONS ALTER COLUMN PERSONID INT IDENTITY(1,1)PRIMARY KEY
-- WILL NOT ALLOW TO DO THIS

ALTER TABLE PERSONS ADD PERSONID_NEW INT IDENTITY(1,1)
ALTER TABLE PERSONS DROP COLUMN PERSONID
EXEC SP_RENAME 'PERSONS.PERSONID_NEW','PERSONID','COLUMN')

--WE CANNOT CREATE IDENTITY COLUMN TO EXISTING TABLE.
--WE CAN ADD NEW COLUMN WITH IDENTITY COLUMN.

--------------------------------------------------------------------------------------------------------

IN FOREIGN KEY, WE CAN USE ONLY ONE COLUMN AS REFERENCE INCASE OF COMPOSITE KEY