--Create a table named as product,hold below column
1. productID
2. productName
3.Price
4.Manufacture
5.ExpiredDate
6.Quantity

SELECT GETDATE()

CREATE TABLE PRODUCT
(
PRODUCTID       INTEGER,
PRODUCTNAME     VARCHAR(30),
PRICE           MONEY,
MANUFACTURE_NAME VARCHAR(30),
[EXPIREDATE]     DATE,
QUANTITY         INTEGER
)

--INSERT RECORDS
-- Safe Method out of all at the beginning
INSERT INTO PRODUCT 
(PRODUCTID,PRODUCTNAME,PRICE,MANUFACTURE_NAME,EXPIREDDATE,QUANTITY)
VALUES
(1,'LAPTOP',1200.25,'DELL','2024-05-17',10)

INSERT INTO PRODUCT
(PRODUCTID,PRICE,MANUFACTURE_NAME,[EXPIREDDATE],QUANTITY,PRODUCTNAME)
VALUES
(2,1200.25,'HP','2024-05-17',10,'LAPTOP')

INSERT INTO PRODUCT 
VALUES
(1,'LAPTOP',1200.25,'DELL','2024-05-17',10)

--if we do not define column order, it will pick original order.

INSERT INTO PRODUCT
VALUES
(2,1200.25,'HP','2024-05-17',10,'LAPTOP')
--Operand type clash: int is incompatible with date

-----INSERTING MULTIPLE RECORDS AT A TIME------------

INSERT INTO PRODUCT
(PRODUCTID,PRODUCTNAME,PRICE,MANUFACTURE_NAME,EXPIREDDATE,QUANTITY)
VALUES
(1,'MONITOR',1200.25,'DELL','2024-05-17',10)

INSERT INTO PRODUCT
(PRODUCTID,PRODUCTNAME,PRICE,MANUFACTURE_NAME,EXPIREDDATE,QUANTITY)

(1,'MONITOR',10000.25,'DELL','2024-05-17',10)

INSERT INTO PRODUCT
(PRODUCTID,PRODUCTNAME,PRICE,MANUFACTURE_NAME,EXPIREDDATE,QUANTITY)
VALUES
(7,'MONITOR',10000.25,'ASUS','2024-05-17',10),
(8,'MONITOR',10000.25,'SAMSUNG','2024-05-18',10),
(9,'MONITOR',10000.25,'APPLE','2024-05-18',10)

--DO NOT WANT TO ENTER VALUE IN EXPIREDATE COLUMN/PUT BLANK IN SOME COLUMN
-- PUT BLANK IN SOME COLUMN
BLANK in varchar value in SQL Server.
BLANK is actually a value in SQL Server.
Skip the column where you do not want to insert value

INSERT INTO PRODUCT
(PRODUCTID,PRODUCTNAME,MANUFACTURE_NAME,QUANTITY)
VALUES
(10,'MONITOR','ANSUS',10)

SELECT *FROM PRODUCT

INSERT INTO PRODUCT
(PRODUCTID,PRODUCTNAME,PRICE,MANUFACTURE_NAME,EXPIREDDATE,QUANTITY)
VALUES
(11,'',10000.25,'DELL','2024-05-17',10)

INSERT INTO PRODUCT
(PRODUCTID,PRICE,MANUFACTURE_NAME,EXPIREDDATE,QUANTITY)
VALUES
(12,10000.25,'DELL','2024-05-17',10)

WE WILL GET DEFAULT DATE IF WE PUT ' '

INSERT INTO PRODUCT
(PRODUCTID,PRODUCTNAME,PRICE,MANUFACTURE_NAME,[EXPIREDDATE],QUANTITY)
VALUES
(13,'',1000.25,'ANSUS','',10

DEFAULT VALUE OF INTEGER IS O

--PRODUCT ID IS REPEATING AS USER ENTER THE PRODUCT ID.

--IDENTITY COLUMN
-- THIS COLUMN VALUE USER NEVER INSERT
-- THIS COLUMN  ALWAYS INCREASE WHEN YOU INSERT NEW ROWS
--1 2 3
-- THIS COLUMN VALUE NEVER GOING TO UPDATE.


CREATE TABLE STUDENTDETAILS
(
SID INT IDENTITY(100,1),
--SID INT IDENTITY OR SID INT IDENTITY (!,1)
--THE FIRST VALUE OF COLUMN IS 1 AND AFTER THAT COLUMN GOING TO UPDATE BY 1
-- BY DEFAULT, IDENTITY COLUMN IS 1,1
-- IF WE NEED SPECIFIC VALUE, WE WILL GIVE VALUE AS SUCH.
-- 'MX' + IDENTITY COLUMN( :CALCULATED/COMPUTED COLUMN
NAME VARCHAR (100)
)

INSERT INTO STUDENTDETAILS (NAME) VALUES('PRATAP')
INSERT INTO STUDENTDETAILS VALUES ('ARINA')
--NEVER PUT VALUE IN IDENTITY COLUMN

SELECT *FROM STUDENTDETAILS

SSMS - INDEPENDENT
SSIS - INTEGRATION SERVICES
SSRS - 

--SQL SERVER SUPPORT ONLY INTEGER IDENTITY

MX2525
MX2526
'MX' + IDENTITY(1,1) - Computed/Calculated Column



