--DCL --- Data Control Language
--Used by database administrator.
--USED TO GRANT OR TAKE BACK THE ACCESS FROM THE USER
--GRANT & REVOKE

GRANT - TO GIVE USER ACCESS PRIVILEGE TO A DATABASE.
Eg: GRANT SELECT,UPDATE ON MY_TABLETO SOME_USER,ANOTHER_USER
REVOKE - TO TAKE BACK PERMISSION FROM THE USER.
Eg: REVOKE SELECT,

GRANT PRIVILEGE_NAME ON OBJECT_NAME
TO USER_NAME

PRIVILEGE_NAME ---> INSERT,UPDATE,CREATE,DELETE,ALTER,TRUNCATE

GRANT INSERT ON DBO.DEPT
TO SHIVA_RAM

GRANT SELECT ON DBO.DEPT
TO SHIVA_RAM

REVOKE INSERT ON DBO.DEPT
FROM SHIVA_RAM

-------------------------------------------------------

--TCL (TRANSACTION CONTROL LANGUAGE)
CAN ONLY USE WITH DML COMMANDS LIKE INSERT, UPDATE AND DELETE ONLY.
AUTOMATICALLY COMMITTED IN THE DATABASE
COMMIT, ROLLBACK, SAVEPOINT
IF THERE IS NO FAILURE, COMMIT TRANSACTION
BLOCKS SUCH AS BEGIN TRY , END TRY, BEGIN CATCH, END CATCH
MOSTLY USED IN STORED PROCEDURES.

--------------------------------------------------------------------------

DQL (DATA QUERY LANGUAGE)
--SELECT----fetching data from a database table

