--USING STORED PROCEDURE FOR UPDATING DATA

SELECT * FROM[dbo].[IntershipRegistration] 

CREATE PROCEDURE [DBO].[UPDATE_REGISTRATIONDATA]
@FULLNAME VARCHAR(100),
@EMAIL VARCHAR(100),
@PRIMCONTACT VARCHAR(100)
AS
BEGIN
	IF EXISTS (SELECT 1 FROM [DBO].[INTERSHIPREGISTRATION] WHERE FULLNAME = @FULLNAME AND EMAIL = @EMAIL)
	BEGIN
		UPDATE [DBO].[INTERSHIPREGISTRATION]
		SET PRIMCONTACT = @PRIMCONTACT
	END
	ELSE
	BEGIN
	   SELECT ('USER HAS ALREADY BEEN CREATED') 
    END
END

SELECT *FROM DBO.INTERSHIPREGISTRATION WHERE FULLNAME='BISHAL THAPA'
EXEC [DBO].[UPDATE_REGISTRATIONDATA] 'BISHAL THAPA','bishal.thapa@gmail.com','5555555555'
SELECT *FROM DBO.INTERSHIPREGISTRATION WHERE FULLNAME='BISHAL THAPA'