
SELECT *FROM ALBUM
SELECT *FROM ALBUM_TYPE
SELECT *FROM ARTIST
SELECT *FROM CITY
SELECT *FROM CONTINENT
SELECT *FROM COUNTRY
SELECT *FROM GENRE
SELECT *FROM PARENT_COMPANY
SELECT *FROM RECORD_LABEL
SELECT *FROM SHOW
SELECT *FROM SUBGENRE
SELECT *FROM TOUR
SELECT *FROM TRACK
SELECT *FROM VENUE
SELECT *FROM VENUE_CATEGORY
SELECT *FROM VENUE_TYPE

SELECT TOP 2 *FROM ALBUM
SELECT TOP 2 *FROM ARTIST
SELECT TOP 2 *FROM SUBGENRE

--1.Create a query to return the following columns from the Album, Artist and Subgenre tables for albums in the @subgenre. 
--By passing subgenre name to stored proc we should get the result for that specific subgenre.

CREATE OR ALTER PROC [DBO].[GETALBUM_ARTIST_SUBGENRE]
	@SUBGENRE NVARCHAR(255)
AS
BEGIN
	IF @SUBGENRE IS NOT NULL AND @SUBGENRE <> ' '
	BEGIN
		SELECT
			A.TITLE,
			A.RELEASE_DATE,
			A.[US_sales_(m)],
			A.US_BILLBOARD_200_PEAK,
			AT.ARTIST,
			AT.ARTIST_TYPE,
			SG.SUBGENRE
			FROM SUBGENRE SG
			JOIN ALBUM A ON SG.SUBGENRE_ID = A.SUBGENRE_ID
			JOIN ARTIST AT ON AT.ARTIST_ID = A.ARTIST_ID
			WHERE SG.SUBGENRE = @SUBGENRE
	END
	ELSE
	BEGIN
		SELECT ('INVALID SUBGENRE PARAMETER')
	END
END

EXEC [DBO].[GETALBUM_ARTIST_SUBGENRE]'HARD ROCK'
EXEC [DBO].[GETALBUM_ARTIST_sUBGENRE]'POP'
EXEC [DBO].[GETALBUM_ARTIST_sUBGENRE]'ART ROCK'
EXEC [DBO].[GETALBUM_ARTIST_sUBGENRE]'GLAM ROCK'
EXEC [DBO].[GETALBUM_ARTIST_sUBGENRE]'ROCK'
EXEC [DBO].[GETALBUM_ARTIST_sUBGENRE]'DANCE'

EXEC [DBO].[GETALBUM_ARTIST_sUBGENRE]'GOD'

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--2.Create a stored proc query to return the following columns from the Artist, Tour and Show tables:

SELECT TOP 2 *FROM ARTIST
SELECT TOP 2 *FROM TOUR
SELECT TOP 2 *FROM SHOW

CREATE PROCEDURE [DBO].[GET_ARTIST_TOUR_SHOW]
AS
BEGIN
SELECT
	AT.ARTIST,
	T.TOUR_NAME,
	SUM(S.TICKETS_SOLD)AS [TOTAL TICKETS SOLD],
	SUM(S.REVENUE_$)AS [TOTAL REVENUE],
	AVG(S.TICKETS_SOLD)AS [AVG TICKETS SOLD],
	AVG(S.Revenue_$) AS [AVG REVENUE]
FROM ARTIST AT
JOIN TOUR T ON AT.ARTIST_ID = T.ARTIST_ID
JOIN SHOW S ON S.TOUR_ID = T.TOUR_ID
GROUP BY AT.ARTIST,T.TOUR_NAME
END

EXEC [DBO].[GET_ARTIST_TOUR_SHOW]