
--WRITE A SCRIPT TO CREATE A TABLE

/*CustomrDetails          1. Id 2.First_Name 3.Last_Name 4.Email 5.Gender 6.Currency
PolygenderMaleBigenderBigenderFemale
RubleDollarPesoYuan RenminbiEuro*/

CREATE TABLE CUSTOMERDETAILS
(
ID           INTEGER,
FIRST_NAME   VARCHAR(25),
LAST_NAME     VARCHAR(25),
EMAIL         VARCHAR(50),
GENDER        VARCHAR(40),
CURRENCY      VARCHAR(25),
DOB           DATE
);

DROP TABLE CUSTOMERDETAILS;

/*CREATE TABLE CUSTOMERDETAILS
(
ID           INT IDENTITY,
FIRST_NAME   VARCHAR(25),
LAST_NAME     VARCHAR(25),
EMAIL         VARCHAR(25),
GENDER        VARCHAR(40),
CURRENCY      VARCHAR(25),
DOB           DATE
);*/

SELECT *FROM CUSTOMERDETAILS;

--Modify datatype of columns - Gender varchar(12), Currency varchar(25)

ALTER TABLE CUSTOMERDETAILS ALTER COLUMN CURRENCY VARCHAR(25) 
ALTER TABLE CUSTOMERDETAILS ALTER COLUMN GENDER VARCHAR(12)

--INSERT DATA BY USING A SINGLE QUERY

INSERT INTO CUSTOMERDETAILS 
(ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,CURRENCY)
VALUES 
(1,'ANTON','PENDERGAST','APENDERGAST0@PARALLELS.COM','POLYGENDER','RUBILE'),
(8,'JEREMIE','ZUPA','JZUPA1@PEN.IO','MALE','DOLLAR'),
(3,'VASSILY','O''SULLIVAN','VOSULLIVAN2@1UND1.DE','BIGENDER','PESO'),
(11,'BERTY','ZANNOTTI','BZANNOTTI3@BANDCAMP.COM','BIGENDER','YUAN RENMINBI'),
(12,'NAHUM','CREAMEN','NCREAMEN4@USTRAM.TV','FEMALE','EURO'),
(20,'EOLANDA','LEDEKER','ELEDEKER5@YOUTUBE.COM','BIGENDER','YUAN RENMINBI'),
(7,'LORENZA','TESH','ITESH6@DISCUZ.NET','BIGENDER','PESO'),
(5,'CORINE','FIDELUS','CFIDELUS7@BEHANCE.NET','GENDERFLUID','SOL'),
(9,'ARLINA','SANDON','ASANDON8@VKONTAKTE.RU','NON-BINARY','YUAN RENMINBI'),
(10,'GIULIO','LINDSEY','GLINDSEY9@NETVIBES.COM','MALE','EURO'),
(11,'AUGY','SWINFORD','ASWINFORDA@ACQUIRETHISNAME.COM','FEMALE','RUPIAH'),
(12,'RENA','ALLMEN','RALLMENB@WASHINGTONPOST.COM','FEMALE','YUAN RENMINBI')

SELECT TABLE NAME ------SCRIPT TABLE AS ----CREATE TO ----NEW QUERY EDITOR WINDOW --- CREATE SCRIPT OF TABLE AND WE CAN COPY SAME TABLE TO OTHER DATABASE.


--We cannot modify identity column using ALTER command.
-- We do not need to enter values for identity column.
-- Whenever we have single apostrophes in between words like O'Sullivan, we have to add one more apostrophe.'O''SULLIVAN'

--WRITE A QUERY TO ADD ONE MORE COLUMN AS CITY.

ALTER TABLE CUSTOMERDETAILS ADD CITY VARCHAR(20)

--currency-->Ruble then City-->Moscowcurrency--> Dollar then City-->New Yorkcurrency--> Peso then City--> Mexicocurrency--> Euro then City--> LondonUPDATE CUSTOMERDETAILSSET CITY='MOSCOW' WHERE CURRENCY='RUBLE'UPDATE CUSTOMERDETAILSSET CITY='NEW YORK' WHERE CURRENCY='DOLLAR'UPDATE CUSTOMERDETAILSSET CITY='MEXICO' WHERE CURRENCY='PESO'UPDATE CUSTOMERDETAILSSET CITY='LONDON' WHERE CURRENCY='EURO'--delete Yuan Renminbi currency data from the tableDELETE FROM CUSTOMERDETAILS WHERE CURRENCY = 'YUAN RENMINBI'SELECT *FROM CUSTOMERDETAILS--Write a query to display City & Currency from customer DetailsSELECT CITY,CURRENCY FROM CUSTOMERDETAILS--QUOTES SHOULD BE USED ONLY WITH VALUES--FOR ADDING ANY COLUMN, WE USE ALTER COMMAND.--FOR MODIFYING DATA, WE USE UPDATE COMMAND.