--AUDIT TRANSFORMATION

TWO SSIS PACKAGE WITH DIFFERENT SOURCES BUT DESTINATION TABLE IS SAME

PACKAGE1 - SOURCE: CSV OR EXCEL FILE
RETURNS 1,2,3
PACKAGE 2 - SOURCE: SQL SERVER TABLE
RETURNS 5,6,7,8



SAME DESTINATION: ONE SINGLE SQL SERVER TABLE
1,2,3,4,5,6,7,8
TO KNOW WHICH RECORD IS INSERTED BY PACKAGE 1 AND WHICH RECORD IS INSERTED BY PACKAGE2?

SOURCE OF RECORDS?
WHAT TIME RECORDS GET INSERTED INTO TABLE?
WHO INSERT RECORDS INTO THIS TABLE?

-- TO KNOW WHICH DATA IN DESTINATION INSERT BY PACKAGE1

EG: WORKING IN APPLE.....CREATING MULTIPLE PACKAGES
PACKAGE1 : ALL SALES DONE BY APPLE STORE DATABASE
PACKAGE2 : ALL SALES DONE BY ONLINE SITE DATABASE
PACKAGE3 : ALL SALES DONE BY LOCAL STORE DATABASE

DESTINATION: SQL SERVER  SALES TABLE

DURING ANALYSIS , WE FOUND ON SALES TABLE SOME DATA IS WRONG, SO WE NEED TO KNOW THE ORIGIN OF DATA
FOR THIS TYPE OF SITUATION, WE USE AUDIT TRANSFORMATION.

WHICH SSIS PACKAGE IS RESPONSIBLE FOR WRONG DATA? USE AUDIT TRANSFORMATION.
WE WILL ADD SOME EXTRA COLUMN LIKE SOURCE OF RECORD,TIME OF INSERTION ETC

MOSTLY PACKAGE NAME, EXECUTION START TIME IS USED FOR AUDIT TRANSFORMATION.
--BEFORE INSERTING RECORD INTO DESTINATION,WE HAVE TO USE AUDIT IN EACH SOURCE
--IF WE MERGE ALL 3 SOURCES AND DO AUDIT, WE GET ONE PACKAGE NAME BUT DATA IS COMING FROM 3 DIFFERENT SOURCES.

--ONE PACKAGE ---- ONE AUDIT
--MULTIPLE PACKAGE ----- MULTIPLE AUDIT

IF WE ARE CREATING MULTIPLE PACKAGES WITH MULTIPLE SOURCES AND SAME DESTINATION, AUDIT TRANSFORMATION IS USEFUL.

SELECT *FROM AUDITEXAMPLE1