--Constraint - define a rule for a column

CREATE TABLE TESTCONSTRAINT
(
NAME VARCHAR(100) NOT NULL, ------CONSTRAINT : NOT NULL
LASTNAME VARCHAR(100) CHECK (LEN(LASTNAME)>5),---CONSTRAINT: CHECK
GENDER CHAR(1) CHECK (GENDER IN ('M','F'),
SSN VARCHAR(20) PRIMARY KEY,
DOB DATE CHECK (DOB BETWEEN '01JUN1950' AND '01JUN2010'),
NATIONALITY VARCHAR(10) DEFAULT ('USA')
)

CREATE TABLE BANKACCOUNT(
ACCOUNTID INT IDENTITY(000001,1),
SSN VARCHAR(20) REFERENCES TESTCONSTRAINT(SSN)
)

--WHENEVER WE WANT TO CREATE PRIMARY KEY, IT SHOULD BE ALWAYS NOT NULL
--FOREIGN KEY CAN BE DUPLICATE BUT PRIMARY KEY CANNOT BE DUPLICATE.
--SSN CANNOT BE DUPLICATE IN TESTCONSTRAINT TABLE BUT IT CAN BE DUPLICATE IN BANKACCOUNT TABLE

UNIQUE CONSTRAINT CAN BE ONE TIME NULL BUT PRIMARY KEY IS NEVER NULL.

IF WE ARE 100% SURE THAT THE COLUMN RECORD CANNOT BE NULL AND DUPLICATE, WE USE PRIMARY KEY.
EG: DRIVING LICENSE UNIQUE - ALL PEOPLE MAY NOT HAVE DRIVING LICENSE 
    SSN NUMBR PRIMARY KEY -- ALL PEOPLE MUST HAVE SSN AND DO NOT ALLOW NULL VALUES

--WE CAN CREATE ONE COLUMN OR COMBINATION OF COLUMN AS A PRIMARY KEY.

DEFAULT CONSTRAINT: IF WE DO NOT PROVIDE ANY VALUE TO THE COLUMN WHILE INSERTING , IT WILL TAKE DEFAULT VALUE.