--ERROR HANDLING
--VARIABLE DECLARATION IN SQL SERVER

DECLARE @V1 INT ,@V2 INT
SET @V1=1
SET @V2=0
SELECT @V1/@V2

SELECT @V1/CASE WHEN @V2=0 THEN 1 ELSE @V2 END
--CLOSING BLOCK OF CASE IS END

--NOTEPAD FILE

ID,NAME,PRICE
1,BOOK,12
2,CHAIR,20
3,PENCIL,TEN RUPEES

WANT TO INSERT THESE RECORDS IN SQL SERVER TABLE

CREATE  TABLE ERRORHANDLING(
ID INT,
NAME VARCHAR,
PRICE DECIMAL (10,2)
)

--RENAME THE TABLE TO ERRORTABLE
exec sp_rename 'errorhandling', 'errortable'


select *from errortable

TRUNCATE TABLE ERRORTABLE

CREATE TABLE ERROR(
ID INT,
NAME VARCHAR,
PRICE DECIMAL (10,2)
)

SELECT *FROM ERROR
