--ERROR HANDLING
--VARIABLE DECLARATION IN SQL SERVER

DECLARE @V1 INT ,@V2 INT
SET @V1=1
SET @V2=0
SELECT @V1/@V2

SELECT @V1/CASE WHEN @V2=0 THEN 1 ELSE @V2 END
--CLOSING BLOCK OF CASE IS END

--NOTEPAD FILE

ID,NAME,PRICE
1,BOOK,12
2,CHAIR,20
3,PENCIL,TEN RUPEES

WANT TO INSERT THESE RECORDS IN SQL SERVER TABLE

CREATE  TABLE ERRORHANDLING(
ID INT,
NAME VARCHAR,
PRICE DECIMAL (10,2)
)

--RENAME THE TABLE TO ERRORTABLE
exec sp_rename 'errorhandling', 'errortable'


select *from errortable
[dbo].[errortable]

TRUNCATE TABLE ERRORTABLE

-----------------------------------------------------------

Source data(varchar)
10
20
one

Data conversion
2 possible solutions - Data converted(10,20)  2.Data not converted (one)

Destination (int,decimal)

Data conversion say that if we got any error message,
We are looking for the datatype of column

--either write Money or decimal(10,2)
--when converting varchar to integer,some values cannot be converted and will throw error.

 SELECT CONVERT(INT,102.23),CONVERT(MONEY,12-----------102
 SELECT CONVERT (MONEY,12.238)
 SELECT CONVERT(DECIMAL(10,2),12.238)
 SELECT CONVERT (MONEY,12.2)
 CONVERT (DECIMAL(10,2),12.2)

 --MONEY HAS SOME EXTRA FEATURE

 SELECT CONVERT(INT, 'TEN')
 IF WE ONLY READ DATA FROM FLAT FILE, WE WILL GET IT BUT WE CANNOT STORE IT. 
 IF THE COLUMN RETURNS ONLY INTEGER BUT SOURCE RETURNS DIFFERENT DATATYPE, DATATYPE COME IN PICTURE.
 WHEN THE SOURCE DATATYPE AND DESTINATION DATATYPE IS DIFFERENT, PROBLEM ARISE.

 3 OPTIONS:
 1.THROW ERROR AND STOP WHOLE PROCESS (FAIL COMPONENT)
 2. IGNORE THE ERROR RECORDS
 3.THROW ERROR RECORDS IN ERROR OUTPUT AND CORRECT RECORDS IN CORRECT OUTPUT

 3OPTION IS THE BEST ONE

 DURING DATA CONVERSION, WE MAY GET ERROR.2 TYPES
 1.ERROR -
 2.TRUNCATION - RELATED TO DATA LENGTH

 SELECT CONVERT(VARCHAR(5),'123456789')------TRUNCATION ERROR

 BEFORE DATA CONVERSION,WE NEED TO CHECK THE DATATYPE OF SOURCE AND DESTINATION.

 FAIL COMPONENT IS BY DEFAULT.......NO DATA
 IGNORE FAILURE ----------DATA THAT IS NOT CONVERTED WILL NE NULL
 REDIRECT ROWS

 CHECK DATATYPE
 DO DATA CONVERSION
 CONFIGURE ERROR OUTPUT

 WE WANT TO HANDLE THE ERROR AND LOG THE ERROR

 LOGGING
 KEEPING THE RECORDS OF ALL STEPS EITHER STEP ARE FAILED OR PASSED.
 EG: MONTHLY STATEMENT
 PAGE Q : SUMMARY
 MONTH NAME : JULY 2024
 OPENING BALANCE:$20
 CLOSING BALANCE : $100

 IF WE WANT TO KNOW DETAILS , WE WILL GO TO PAGE 2
 DATE | DESCRIPTION |TYPE(DR/CR) | AMOUNT

 LOGGING HELPS TO RECALL THE PROCESS

 ERROR HANDLING AND ERROR LOGGING IS DIFFERENT PROCESS.
 ERROR HANDLING IS TOTALLY DIFFERENT FROM LOGGING. YES

  ERROR HANDLING SAYS THAT IF YOU GOT ANY ERROR, HOW DO YOU HANDLE THE ERROR?3 OPTIONS
  WE HAVE TO WAIT FOR ERROR TO INVOKE ERROR HANDLING
  ERROR LOGGING CANNOT FIX THE ERROR AND HAVE NO 3 OPTIONS.IT SAYS YOU GOT ERROR OR SUCCESS AND CAPTURE EVERY  STEP

  AUDIT TRANSFORMATION OCCURS ONLY WHEN THE PROCESS COMPLETES SUCCESSFULLY

  ERROR HANDLING MEANS  IDENTIFYING THE ERROR AND HOW TO HANDLE THE ERROR.
  LOGGING MEANS JUST NOTING DOWN WHETHER SUCCESS OR FAILURE.
  LOGGING IS LIKE NEIGHBOUR.

  LOGGING CONFIGURED IN PACKAGE LEVEL.

  BENEFIT OF LOGGING
  WHEN WE LEARN ANY TOPIC, WE ASK WHAT,WHY,HOW?
  IN THE CORPORATE, IF SOMEONE SAY THAT DATA IS NOT COMING TO MY DESTINATION ON A PARTICULAR DAY AND WHY? IF WE DO NOT HAVE LOGGING WE CANNOT SAY.
  LIKE BOOKKEEPING IN ACCOUNTANT
  EVERY YEAR, COMPANY LAUNCH PL(PROFIT/LOSS)AC 
  LEDGER ENTRY - HISTORY OF EACH AND EVERY DEBIT AND CREDIT ACCOUNT
  BEFORE LEDGER, WE CREATE JOURNAL ACCOUNT

  IF WE DO NOT IMPLEMENT LOGGING WE CANNOT FIGURE OUT HOW MANY TIMES SSIS PACKAGE IS PASSED AND HOW MANY TIMES IT IS FAILED?

  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  
  SELECT *FROM SYSSSISLOG
 -- Invalid object name 'SYSSSISLOG'.










  
