CREATE TABLE TEST1
( ID INT
)

CREATE TABLE TEST2
(ID INT
)

INSERT INTO TEST1 (ID) VALUES (1)
INSERT INTO TEST1 (ID) VALUES (1)
INSERT INTO TEST1 (ID) VALUES (1)
INSERT INTO TEST1 (ID) VALUES (1)
INSERT INTO TEST2 (ID) VALUES (1)
INSERT INTO TEST2 (ID) VALUES (1)
INSERT INTO TEST2 (ID) VALUES (1)

SELECT *FROM TEST1
SELECT *FROM TEST2




SELECT *FROM TEST1 AS T1
JOIN TEST2 AS T2
ON T1.ID = T2.ID

SELECT *FROM TEST1 AS T1
LEFT JOIN TEST2 AS T2
ON T1.ID = T2.ID

SELECT *FROM TEST1 AS T1
RIGHT JOIN TEST2 AS T2
ON T1.ID = T2.ID

SELECT *FROM TEST1 AS T1
CROSS JOIN TEST2 AS T2

SELECT * FROM STUDENT_SSIS



CREATE TABLE SUBJECT
(
ID INT IDENTITY,
SUBJECTNAME VARCHAR(100),
STUDENTID INT
)

INSERT INTO SUBJECT VALUES ('DBMS',1)
INSERT INTO SUBJECT VALUES ('DBMS',2)
INSERT INTO SUBJECT VALUES ('DBMS',3)
INSERT INTO SUBJECT VALUES ('DBMS',4)
INSERT INTO SUBJECT VALUES ('DBMS',5)

INSERT INTO SUBJECT VALUES ('JAVA',1)
INSERT INTO SUBJECT VALUES ('JAVA',2)
INSERT INTO SUBJECT VALUES ('JAVA',3)
INSERT INTO SUBJECT VALUES ('JAVA',4)

INSERT INTO SUBJECT VALUES ('C++',1)
INSERT INTO SUBJECT VALUES ('C++',2)
INSERT INTO SUBJECT VALUES ('C++',3)

INSERT INTO SUBJECT (SUBJECTNAME) VALUES('C#')

SELECT *FROM SUBJECT

--WE HAVE TWO TABLES TO MAINTAIN ACID PROPERTIES IN DBMS

--STUDENT NAME WHO OPT DBMS SUBJECT
SELECT A.FIRSTNAME + ' ' + A.LASTNAME  FROM STUDENT_SSIS AS A
JOIN SUBJECT AS B
ON A.ID = B.STUDENTID
WHERE B.SUBJECTNAME = 'DBMS'
--COMBINE TWO TABLE, TAKE ALL THE RECORDS AND THEN APPLY FILTER.

SELECT A.FIRSTNAME + ' ' + A.LASTNAME  FROM STUDENT_SSIS AS A
JOIN SUBJECT AS  B
ON A.ID = B.STUDENTID AND B.SUBJECTNAME = 'DBMS'
--WHILE JOINING ONLY, SAY THAT JOIN WHERE SUBJECTNAME = 'DBMS'

--WE NEED TO WRITE OPTIMIZED QUERY.

WHENEVER COMBINING TWO TABLES, WE ARE LOOKING FOR COMMON VALUE COLUMN.