--SCD - Slowing Change Dimension
TYPE O - FIXED. EG: SOCIAL SECURITY NUMBER, PASSPORT NUMBER
TYPE 1 - OVERWRITE THE OLD NAME AND WE DONOT MAINTAIN HISTORY. EG: CHANGE NAME A ----> B
TYPE 2 - WE MAINTAIN CHANGE HISTORY.EG: ADDRESS

WHEN APPLYING SCD, WE NEED ONE COLUMN AS A PRIMARY KEY CALLED BUSINESS KEY
KEY - A COLUMN WHERE VALUE CAN BE UNIQUE.

Product table
ID  | Name | Unit Price
1     Book      12


--	Create Transaction Table

CREATE TABLE [dbo].[Supplier](
[SupplierCode] CHAR(8) PRIMARY KEY,
[SupplierName] [varchar](50) NULL,
[Address] [varchar](50) NULL,
) ON [PRIMARY]
--Primary key at source and will work as a business key

--Add value in Transaction table

INSERT INTO [dbo].[Supplier] ([SupplierCode], [SupplierName], [Address])
VALUES
('S0000001', 'ABC Company', 'USA'),
('S0000002', 'XYZ Corporation', 'USA')

--Select value from transaction table
SELECT * FROM [dbo].[Supplier]

--Create Dim table

CREATE TABLE [dbo].[DimSupplier](
[SupplierId] [int] IDENTITY(1,1) NOT NULL,
[SupplierCode] CHAR(8),
[SupplierName] [varchar](50) NULL,
[Address] [varchar](50) NULL,
[EffectiveDate] [date] NULL,
[ExpirationDate] [date] NULL,
[CurrentFlag] [char](1) NULL,
CONSTRAINT [PK_DimSupplier] PRIMARY KEY CLUSTERED ([SupplierId] ASC)
) ON [PRIMARY]

SELECT *FROM SUPPLIER
SELECT *FROM DIMSUPPLIER

--UPDATE
--MAKE CHANGES IN SUPPLIER TABLE,EXECUTE IN SSMS ,RUN SSIS PACKAGE AND THEN ONLY RUN SELECT *FROM DIMSUPPLIER TABLE TO SEE CHANGES IN DIMTABLE AFTER UPDATE COMMAND

UPDATE SUPPLIER SET ADDRESS = 'NEPAL' WHERE SUPPLIERCODE = 'S0000001'

--TO KNOW CURRENT ADDRESS,
SELECT S.*FROM DIMSUPPLIER AS S
JOIN (
SELECT SUPPLIERCODE,MAX(SUPPLIERID)AS SUPPLIERID FROM DIMSUPPLIER GROUP BY SUPPLIERCODE)AS S2
ON S.SUPPLIERID = S2.SUPPLIERID

--IF ONLY *, ALL THE COLUMNS AVAILABLE IN TABLE 1 AND TABLE 2
-- IF S.* ,NEED ALL THE COLUMNS FROM S TABLE,FIRST TABLE  ONLY

--WE HAVE EFFECTIVE DATE,EXPIRY DATE IN DIMSUPPLIER TABLE

IF USER CHANGE SUPPLIER NAME, THEN IT IS SCD TYPE 1 IN DIM SUPPLIER TABLE
IF CHANGE ADDRESS: SCD TYPE 2 IN DIM SUPPLIER

--3 METHODS TO MAINTAIN HISTORICAL DATA (2 COLUMNS ADD OR 1 COLUMN TO MAINTAIN HISTORICAL DATA


SUPPLIERCODE | SUPPLIERNAME | ADDRESS
S0000001 | ABC Company | USA | JAN 2023 | 31 JAN 2023
S0000001 | ABC Company | INDIA | 31 JAN 2023 | 31 JAN 2024
S0000001 | ABC Company | NEPAL |1 FEB 2024 |

--TO KNOW THE CURRENT ADDRESS
SELECT *FROM SUPPLIER WHERE ENDDATE IS NULL

ABC COMPANY ----? ABC COMPANY LLM
FACEBOOK - META

SUPPLIERCODE | SUPPLIERNAME | ADDRESS | EXPIRED
S0000001 | ABC Company | USA | YES
S0000001 | ABC Company | INDIA | YES
S0000001 | ABC Company | NEPAL |NO

SELECT *FROM SUPPLIER WHERE EXPIRED = 'NO'

SUPPLIERCODE | SUPPLIERNAME | ADDRESS
S0000001 | ABC Company | USA | 31 JAN 2023
S0000001 | ABC Company | INDIA | 31 JAN 2024
S0000001 | ABC Company | NEPAL |

--HISTORICAL ATTRIBUTE OPTIONS
S0000001 | ABC Company | INDIA |CURRENT
S0000001 | ABC Company | NEPAL |TRUE

--AFTER CONFIGURING SCD AND RUNNING SSIS PACKAGE, WHAT DATA IS GOING TO STORE IN DIMSUPPLIERTABLE?
SELECT *FROM SUPPLIER
SELECT *FROM DIMSUPPLIER

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

--TRUNCATE TABLE SUPPLIER
--TRUNCATE TABLE DIMSUPPLIER

UPDATE SUPPLIER SET SUPPLIERNAME = 'NEPAL' WHERE SUPPLIERCODE = 'S0000001'

UPDATE SUPPLIER SET SUPPLIERNAME = 'MNO' WHERE SUPPLIERCODE = 'S0000001'
--??CAN WE UPDATE CHANGING ATTRIBUTES MORE THAN ONCE?

UPDATE SUPPLIER SET ADDRESS = 'INDIA' WHERE SUPPLIERCODE = 'S0000001'

/*WE ALWAYS PERFORM INSERT,UPDATE,DELETE IN SUPPLIER TABLE

-------------------------------------------------------------------------------------------------------------------------------------------------------------------

--PRACTICE*/

CREATE TABLE STAGINGCUSTOMER
(
CUSTOMERID INT,
CUSTOMERNAME NVARCHAR(100),
ADDRESS NVARCHAR(100),
CITY NVARCHAR(50),
STATE NVARCHAR(50),
ZIPCODE NVARCHAR(20)
)

INSERT INTO STAGINGCUSTOMER VALUES
(1,'SACHIN','2822 LONG SLOPE ROAD','ARLINGTON','TEXAS','76001'),
(2,'ARI','188 GANGALAL MARG','PLANO','OHIO','72001'),
(3,'SANTOSH','200 LONESOME DRIVE','SPOKAN','WASHINGTONDC','72000')

--DIMENSION TABLE
--FOR SCD TYPE 1
CREATE TABLE DIMCUSTOMERTYPE1 (
CUSTOMERID INT PRIMARY KEY,
CUSTOMERNAME NVARCHAR(100),
ADDRESS NVARCHAR(100),
CITY NVARCHAR(50),
STATE NVARCHAR(50),
ZIPCODE NVARCHAR(20)
)


--FOR SCD TYPE 2
CREATE TABLE DIMCUSTOMERTYPE2 (
SURROGATEKEY INT IDENTITY (1,1)PRIMARY KEY,
CUSTOMERID INT,
CUSTOMERNAME NVARCHAR(100),
ADDRESS NVARCHAR(100),
CITY NVARCHAR(50),
STATE NVARCHAR(50),
ZIPCODE NVARCHAR(20),
EFFECTIVEDATE DATETIME,
EXPIRYDATE DATETIME,
ISCURRENT BIT
)

SELECT *FROM STAGINGCUSTOMER
SELECT *FROM DIMCUSTOMERTYPE1

--UPDATE
UPDATE STAGINGCUSTOMER
SET CITY='DALLAS' 
WHERE CUSTOMERID = 1

--SCD TYPE 2

SELECT *FROM STAGINGCUSTOMER
SELECT *FROM DIMCUSTOMERTYPE2

--UPDATE


UPDATE STAGINGCUSTOMER
SET ADDRESS = '2000 LONG SLOPE'
WHERE CUSTOMERID =1

UPDATE STAGINGCUSTOMER
SET ADDRESS = '1000 LONG SLOPE ROAD'
WHERE CUSTOMERID = 1

UPDATE STAGINGCUSTOMER
SET ADDRESS = '200 GANGALAL'
WHERE CUSTOMERID = 2

UPDATE STAGINGCUSTOMER
SET ADDRESS = '100 LONESOME'
WHERE CUSTOMERID = 3

select *from studentaudit

-------------------------------------------------------------------------------------------------------

CREATE TABLE CUSTOMERINFO
(
CUSTOMERID INT PRIMARY KEY,
CUSTOMERNAME VARCHAR(35),
ADDRESS VARCHAR (50),
MEMBERSHIPLEVEL VARCHAR(20),
ISACTIVE CHAR(4)
)

DROP TABLE DIMCUSTOMERINFO

CREATE TABLE DIMCUSTOMERINFO
(
CUSTOMERID INT PRIMARY KEY,
CUSTOMERNAME VARCHAR(35),
ADDRESS VARCHAR (50),
MEMBERSHIPLEVEL VARCHAR(20),
ISACTIVE CHAR(4),
STARTDATE DATE,
ENDDATE DATE
)

UPDATE DIMCUSTOMERINFO
SET STARTDATE = GETDATE();


SELECT *FROM DIMCUSTOMERINFO

INSERT INTO CUSTOMERINFO VALUES (1 ,'John Doe','123 Elm St','Silver','Yes')
INSERT INTO CUSTOMERINFO VALUES (2 ,'Jane Smith','789 Pine St','Bronze','Yes')
INSERT INTO CUSTOMERINFO VALUES (3 ,'Bob Brown','321 Maple St','Silver','Yes')
INSERT INTO CUSTOMERINFO VALUES (4 ,'Alice Green','987 Cedar St','Bronze','Yes')
INSERT INTO CUSTOMERINFO VALUES (5 ,'Carol White','543 Spruce St','Silver','Yes')
INSERT INTO CUSTOMERINFO VALUES (6 ,'Dave Black','135 Oak St','Bronze','Yes')
INSERT INTO CUSTOMERINFO VALUES (7 ,'Emma Gray','246 Elm St','Silver','Yes')
INSERT INTO CUSTOMERINFO VALUES (8 ,'Frank Blue','357 Pine St','Bronze','Yes')
INSERT INTO CUSTOMERINFO VALUES (9 ,'Grace Pink','468 Maple St','Silver','Yes')
INSERT INTO CUSTOMERINFO VALUES (10,'Hank Red','579 Birch St','Bronze','Yes')

SELECT *FROM CUSTOMERINFO







