--CONDITIONAL SPLIT

SELECT *FROM STUDENT_SSIS

INSERT INTO STUDENT_SSIS VALUES ('SUSHOBJIT','RAMAN','T','09MAY1991',12,23,34,45,56)

1 FILE CONTAIN ONLY MALE EMPLOYEE INFORMATION
SELECT *FROM STUDENT_SSIS WHERE GENDER = 'M'
1 FILE CONTAIN ONLY FEMALE EMPLOYEE DATA 
SELECT *FROM STUDENT_SSIS WHERE GENDER = 'F'

SELECT *FROM STUDENT_SSIS WHERE GENDER = 'T'

--SALE TABLE
--I WANT TO TAKE CARE OF INDIA SALE'S DATA BUT I HAVE ALL COUNTRIES DATA. IN THAT CASE,WE USE CONDITIONAL SPLIT.

UPDATE STUDENT_SSIS SET GENDER = 'm' WHERE ID IN (1,2)

UPDATE STUDENT_SSIS SET SUB5 =50 WHERE ID IN (1,2,6)
SELECT LOWER ('RAMAN.SUSHOBHIT'),LOWER('RAMAN.SUSHOBHIT')

SELECT *FROM STUDENT_SSIS WHERE GENDER = 'M' AND SUB5 = 50

--WANT TO SEE ASIA SALES WHEN WE HAVE COUNTRIES COLUMN ONLY
-- WE USE OR OPERATOR OR IN OPERATOR.
--SSIS ALLOW 2 CONDITIONS

0 AND 1 = 0
SELECT 0*1
0+1=1
SELECT 1+0

AND - *
OR - +
NOT

----------------------------------------------------------------------------------------------------------------------------------------------------


