
--TEST 4 QUERY

--Q.NO.2

SELECT O.[CUSTOMER NAME],COUNT(O.[ORDER ID)]FROM ORDERS$ AS O
LEFT JOIN RETURNS$ AS R
ON O.[ORDER ID]=R.[ORDER ID]
WHERE R.[ORDER ID] IS NULL
GROUP BY O.[CUSTOMER NAME]


--Q.NO.3
SELECT [ORDER ID],SUM(SALES),SUM(PROFIT),SUM(QUANTITY) FROM ORDERS$
GROUP BY [ORDER ID]
-- IN ORDER ID , WE DID NOT APPLY ANY NUMERICAL CALCULATION.