
--CUSTOM DATATYPE
--DERIVED DATATYPE / USER DEFINED DATATYPE
CREATE TYPE [DBO].[PHONENUMBER]FROM [NVARCHAR](20) NOT NULL

CREATE TABLE TEST 
(
PHONENO1 NVARCHAR(20),
PHONENO2 NVARCHAR(20) NOT NULL,
PHONEN03 PHONENUMBER
)

--EMAIL ADDRESS
RULE1 : ALWAYS NVARCHAR
RULE2 : ALWAYS START WITH A CHARACTER
RULE3 : IT ALWAYS CONTAIN @
RULE4 : IT ALWAYS CONTAIN ATLEAST ONE .
