DROP TABLE IF EXISTS STUDENT

CREATE TABLE STUDENT
(
ID INT,
NAME VARCHAR(20),
GENDER CHAR(3)
)

CREATE VIEW VW_STUDENT1
AS
SELECT ID,NAME--,GENDER
FROM STUDENT

ALTER TABLE STUDENT ADD  DOB DATE

--If we add any column to a base table after view creation, the added column is not reflected in view.

ALTER TABLE STUDENT DROP COLUMN GENDER

insert into student values (1,'ram','m')
CREATE VIEW view_name AS
SELECT column1, column2, ...
FROM table_name
WHERE condition;

select *from student
SELECT *FROM VW_STUDENT1

2 column - 

INSERT INTO VW_STUDENT1(ID)VALUES(3)

EXEC sp_refreshview VW_STUDENT1

DROP TABLE CLASS
CREATE TABLE CLASS(
CLASSID INT,
CLASSNAME VARCHAR(10)
)

CREATE VIEW VW_CLASS1
AS 
SELECT *FROM STUDENT AS A
JOIN CLASS AS C
ON A.ID = C.CLASSID

INSERT INTO VW_CLASS1 (ID,NAME,CLASSID,CLASSNAME) VALUES (1,'ARINA',1,'SSIS')

SELECT *FROM CLASS
SELECT *FROM VW_CLASS1
IF WE HAVE A SINGLE TABLE, VIEW ALLOW INSERT COLUMN/INSERT DATA OPERATION.
IF WE HAVE MULTIPLE TABLE, view DO NOT ALLOW ANY OPERATION


