--SQL SERVER DATE FUNCTIONS

--CURRENT TIMESTAMP- RETURNS THE CURRENT DATE AND TIME
--DATEADD - ADDS A TIME/DATE INTERVAL TO A DATE AND THEN RETURNS THE DATE
--DATEDIFF - RETURNS THE DIFFERENCE BETWEEN TWO DATES
--DATEFROMPARTS
--DATENAME
--DATEPART
--DAY
--GETDATE
--GETUTCDATE
--ISDATE
--MONTH
--SYSDATETIME
--YEAR

--FOUR FUNCTIONS RETURNING CURRENT DATE AND TIME
CURRENT TIMESTAMP
RETURNS THE CURRENT DATE AND TIME
'YYYY-MM-DD hh:..:ss:mmm' format
SELECT CURRENT_TIMESTAMP

GETDATE()
RETURNS THE CURRENT DATABASE SYSTEM DATE AND TIME IN A 'YYYY-MM-DD hh:..:ss:mmm' format
SELECT GETDATE()

GETUTCDATE()
RETURNS THE CURRENT DATABASE SYSTEM UTC DATE AND TIME
SELECT GETUTCDATE()

SYSDATETIME()
RETURNS THE DATE AND TIME OF THE COMPUTER WHERE THE SQL SERVER IS RUNNING
SELECT SYSDATETIME()

DATEADD()
ADDS A TIME/DATE INTERVAL TO A DATE AND THEN RETURNS THE DATE
SYNTAX: SELECT DATEADD(INTERVAL,NUMBER,DATE)

SELECT DATEADD(YEAR,1,'2024/06/14')AS YEARADD--- IT WILL ADD 1 YEAR TO DATE
SELECT DATEADD(MONTH,2,'2024/06/14')AS DATEADD--WILL ADD 2 MONTHS TO DATE
SELECT DATEADD(MONTH,-2,'2024/06/14')AS DATEADD ---WILL ADD -2 MONTHS TO DATE

SELECT GETDATE()
SELECT DATEADD(HH,3,GETDATE())AS DATEADD
SELECT DATEADD(MINUTE,30,GETDATE())AS DATEADD
--WE CAN ADD HOUR,MINUTES,SECOND PART AS WELL

--DATEDIFF()
RETURNS THE DIFERENCE BETWEEN TWO DATES
SYNTAX: SELECT DATEDIFF(INTERVAL,DATE1,DATE2)

SELECT DATEDIFF(MONTH,'2024/08/25','2024/08/25')AS DATEDIFF-- DISPLAYS DIFF BETWEEN GIVEN DATES IN MONTH

SELECT DATEDIFF(MONTH,'2024/08/25','2024/06/01')AS DATEDIFF
SELECT DATEDIFF(YEAR,'2020/08/25','2024/06/01')AS DATEDIFF
SELECT DATEDIFF(DAY,'2024/06/25','2024/06/01')AS DATEDIFF
SELECT DATEDIFF(HOUR,'2024/08/25 07:00','2024/06/01 12:45')AS DATEDIFF

--TO FIND THE AGE OF EACH EMPLOYEE
SELECT BUSINESSENTITYID,NATIONALIDNUMBER,BIRTHDATE,DATEDIFF(YEAR,BIRTHDATE,GETDATE())AS AGE FROM [HUMANRESOURCES].[EMPLOYEE]

--FIND EMPLOYEES WHO ARE GOING TO RETIRE
SELECT BUSINESSENTITYID,NATIONALIDNUMBER,BIRTHDATE,DATEDIFF(YEAR,BIRTHDATE,GETDATE())AS AGE 
FROM [HUMANRESOURCES].[EMPLOYEE]
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >= 50

--TO FIND AGE OF EACH EMPLOYEE AFTER 10 YEARS
SELECT BUSINESSENTITYID,NATIONALIDNUMBER,BIRTHDATE,DATEDIFF(YEAR,BIRTHDATE,GETDATE()),
(DATEDIFF (YEAR,BIRTHDATE,GETDATE())+10)AS AGE 
FROM [HUMANRESOURCES].[EMPLOYEE]

--SELECT DATEDIFF( -----AUTOMATICALLY SHOW THE REQUIRED PARAMETERS.
--WHATEVER THE DATE SHOULD BE GIVEN VALID DATE ONLY.

--EMPLOYEES WHO JOINED IN THE YEAR 2007

SELECT *FROM 

--DATEFROMPARTS()
--RETURNS A DATE FROM THE SPECIFIED PARTS(YEAR,MONTH AND DAY)VALUES
SYNTAX: SELECT DATEFROMPARTS(2018,10,31)AS DATEFROMPARTS

SELECT DATEFROMPARTS(2018,10,31)AS DATEFROMPARTS

DATENAME()
RETURNS A SPECIFIED PART OD A DATE AND RETURNS THE RESULT AS A STRING VALUE
SYNTAX: SLECT DATENAME(INTERVAL,DATE)

SELECT DATENAME(YEAR,'2017/08/25')AS DATEPARTSTRING
SELECT DATENAME(YYYY,'2017/08/25')AS DATEPARTSTRING
SELECT DATENAME(YY,'2017/08/25')AS DATEPARTSTRING
SELECT DATENAME(MONTH,'2017/08/25')AS DATEPARTSTRING
SELECT DATENAME(HOUR,'2017/08/25')AS DATEPARTSTRING
SELECT DATENAME(MINUTE,'2017/08/25')AS DATEPARTSTRING

DATEPART()
RETURNS A SPECIFIED PART OF A DATE
RETURNS THE RESULT AS AN INTEGER VALUE 
SELECT DATEPART(INTERVAL,DATE)

SELECT DATEPART(MINUTE,'2017/08/25 08:36')AS DATEPARTINT

ISDATE()
CHECKS AN EXPRESSION AND RETURNS 1 IF IT IS A VALID DATE OTHERWISE O
SYNTAX: ISDATE(EXPRESSION)

SELECT ISDATE('2023-08-14')
SELECT ISDATE('9999-08-14') --WE HAVE A VALID CALENDAR UPTO '9999'
SELECT ISDATE('HELLO')
SELECT ISDATE('2000')
--WILL SEE ENTIRE DATE VALUE TO CHECK BUT TAKE YEAR ALONE AS WELL

--DAY,MONTH,YEAR
SYNTAX:SELECT DAY/MONTH/YEAR(DATE)

DAY() RETURNS THE DAY OF THE MONTH(FROM 1 TO 31)FOR A SPECIFIED DATE(FROM 1 TO 31)
MONTH()RETURNS THE MONTH PART OF A SPECIFIED DATE
YEAR() RETURNS THE YEAR PART FOR A SPECIFIED DATE

SELECT YEAR('1998/05/25 09:08')AS YEAR

--FIND ALL EMPLOYEES WHOSE HIREDATE IS 2007
SELECT *FROM [HUMARNRESOURCES].[EMPLOYEE]WHERE YEAR(HIREDATE)='2007'

SELECT *FROM [HUMARNRESOURCES].[EMPLOYEE]WHERE HIREDATE BETWEEN '2007/01/01' AND '2007/12/31'

SELECT *FROM [HUMARNRESOURCES].[EMPLOYEE]WHERE HIREDATE > '2007/01/01' AND HIREDATE < '2007/12/31'

--TWO WAYS OF COMMENTING
-- FOR A SINGLE LINE  &/*   */ FOR MULTIPLE LINES