--DDL TRIGGERS
--FIRE IN RESPONSE TO DDL EVENTS-CREATE,ALTER AND DROP (TABLE,FUNCTION,INDEX,STORED PRODEDURE ETC)
--USED MOSTLY BY DATABASE ADMINISTRATOR
--TWO TYPES OF SCOPE ON DDL TRIGGER - SERVER LEVEL AND DATABASE LEVEL
--https://learn.microsoft.com/en-us/sql/relational-databases/triggers/ddl-events?view=sql-server-ver16&redirectedfrom=MSDN
--SERVER LEVEL TRIGGER IS STORED IN SERVER OBJECTS
--DATABASE LEVEL TRIGGER IS STORED UNDER PROGRAMMABILITY.

CREATE TABLE GAMES
(
GAMEID INT,
NAME VARCHAR(5)
)
SELECT EVENTDATA()

--SERVER TRIGGER
CREATE OR ALTER TRIGGER TR_CREATEOBJECTS
ON ALL SERVER
FOR CREATE_TABLE,ALTER_TABLE,DROP_TABLE,CREATE_DATABASE
AS
BEGIN
	SELECT EVENTDATA()
	PRINT 'A NEW OBJECT HAS BEEN CREATED'
	--ROLLBACK
	--PRINT"YOU CANNOT CREATE,ALTER OR DROP A TABLE IN ANY DATABASE ON THE SERVER'
END

CREATE DATABASE OLYMPICS

--STANDARD EVENT TYPES IN MICROSOFT

--WE CAN AVOID NEW OBJECT CREATION WITHIN THE SERVER
--FOR GRANTING,ACCESSING OR CAPTURING ALL OF THE CHANGES IN THE DATABASE.
--EVENTDATA() CAN BE ACCESSED WITHIN THE CONTEXT OF TRIGGER BODY.

--WITHOUT DELETING THE TRIGGER, WE CAN DISABLE THE TRIGGER.
--THERE ARE 2 WAYS WE CAN DROP THE TRIGGER - DIRECTLY DROP SYNTAX OR RT CLICK ---- DISABLE.

--WE CAN CREATE SERVER LEVEL TRIGGER TO DENY THE LOGIN 

--DATABASE TRIGGERS
CREATE OR ALTER TRIGGER TR_GETAUDITINFO
ON DATABASE
FOR CREATE_TABLE,CREATE_PROC,DROP_TABLE
BEGIN
	SELECT EVENTDATA()
	SELECT 'A NEW OBJECT HAS BEEN CREATED IN OLYMPICS DATABASE'
END

CREATE TABLE CLAIMS
(CLCL_ID VARCHAR(12),
INPUT_DT DATETIME
)

--TO LOAD DATA (XML DATA ) INTO AUDITTABLEINFO
END

WE ARE NOT ALLOWING TO CREATE TABLE BUT TRACK INFORMATION ON WHO HAS CREATED TABLE

--XML DATATYPE IS CASE SENSITIVE

--LOGON TRIGGER