CREATE FUNCTION DBO.FN_NUMBERTOWORDS
(
@NUMBER BIGINT
)
RETURNS VARCHAR (1000)
AS
BEGIN
	DECLARE @BELOW20 TABLE
	(
	 ID INT IDENTITY(0,1),
	 WORD VARCHAR(50)
	 )

	 DECLARE @BELOW100 TABLE
	 (
	 ID INT IDENTITY(2,1),
	 WORD VARCHAR(50)
	 )

	 INSERT INTO @BELOW20 (WORD)
	 ('ZERO
	 ('ONE
	 ('TWO 
	 ('THREE
	 ('FOUR
	 ('FIVE
	 ('SIX
	 ('SEVEN
	 ('EIGHT
	 ('NINE
	 ('TEN
	 ('ELEVEN
	 ('TWELVE
	 ('THIRTEEN
	 ('FOURTEEN
	 ('FIFTEEN
	 ('SIXTEEN
	 ('SEVENTEEN
	 ('EIGHTEEN
	 ('NINETEEN

	 INSERT INTO @BELOW100 (WORD)VALUES
	 (
	 Twenty,
	 Thirty,
	 Fourty, 
	 Fifty, 
	 sixty Seventy, Eighty, Ninety, Hundred)

	 DECLARE @ENG_WORD VARCHAR(1000)
	 =(
	    SELECT 
		    CASE WHEN @NUMBER = 0 THEN 'ZERO'
			     WHEN @NUMBER BETWEEN 1 AND 19 
				     THEN (SELECT WORD FROM @BELOW20 WHERE ID = @NUMBER)
                  WHEN @NUMBER BETWEEN  20 AND 99----THIRTY FIVE
				      THEN (SELECT WORD FROM @BELOW100 WHERE ID = @NUMBER/10) + ' ' + DBO.FN_NUMBERTOWORDS(@NUMBER%10)
				  WHEN @NUMBER BETWEEN  100 AND 999----ONE HUNDRED ONE
				      THEN (SELECT WORD FROM @BELOW100 WHERE ID = @NUMBER/100) + ' HUNDRED ' + DBO.FN_NUMBERTOWORDS(@NUMBER%100)
                 WHEN @NUMBER BETWEEN  1000 AND 999999
				      THEN (SELECT WORD FROM @BELOW100 WHERE ID = @NUMBER/1000) + 'THOUSAND ' + DBO.FN_NUMBERTOWORDS(@NUMBER%1000)
			     WHEN @NUMBER BETWEEN  1000000 AND 999999999
				      THEN (SELECT WORD FROM @BELOW100 WHERE ID = @NUMBER/1000000) + 'MILLION ' + DBO.FN_NUMBERTOWORDS(@NUMBER%1000000)
				  WHEN @NUMBER BETWEEN  1000000000 AND 999999999999
				      THEN (SELECT WORD FROM @BELOW100 WHERE ID = @NUMBER/1000000) + 'BILLION ' + DBO.FN_NUMBERTOWORDS(@NUMBER%1000000000)
                  WHEN @NUMBER BETWEEN  1000000000000 AND 999999999999999
				      THEN (SELECT WORD FROM @BELOW100 WHERE ID = @NUMBER/1000000) + 'TRILLION ' + DBO.FN_NUMBERTOWORDS(@NUMBER%1000000000)
                  ELSE 'INVALID INPUT'
				END
			)

			SELECT @ENG_WORD = RTRIM(LEFT(@ENG_WORD,LEN(@ENG_WORD)-1)) WHERE RIGHT(@ENG_WORD,1)=' '

			RETURN @ENG_WORD

END
					  SELECT 99%10
					  121

					  --WE WANT TO RETURN KEYWORDS LIKE MILLION,BILLION BUT ARE NOT STORING
					  WE ARE CALLING FUNCTION AGAIN AND AGAIN TO GET EXPECTED RESULT

					  WE ARE GETTING WORD FROM VALUES