--PIVOT OPERATOR IN SQL SERVER

--USED FOR ROTATING A TABLE 
--WE WILL SEE UNIQUE VALUES IN A COLUMN

WHATEVER COLUMN WE ARE CONSIDERING AS A UNIQUE COLUMN IS PIVOTED COLUMN.
NON PIVOTED COLUMN ARE THOSE WHERE WE ARE NOT DOING ANYTHING.
PIVOT COLUMNS ARE NOT PRESENT IN THE FORM OF COLUMN, SO WE HAVE TO CONVERT.
--ROWS VALUES IS CONVERTED TO COLUMNS.
-- PIVOT OPERATOR IS MOSTLY USED IN AGGREGATE FUNCTIONS
-- when there is redundant data avaiable to 

--pivot operator turns row values into columns where as unpivot turns columns into rows.
--As we are deriving the column,we can have any column name.
